<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Abstracts\Model;

class User extends Model
{

    protected ?int $id;
    protected ?string $name;
    protected ?string $email;
    protected ?string $password;
    protected ?string $createdAt;
    protected ?string $updatedAt;
    

    public function __construct(?int $id = null, ?string $name = null, ?string $email = null, ?string $password = null, ?string $createdAt = null, ?string $updatedAt = null)
    {
        $this->id = $id;
	    $this->name = $name;
	    $this->email = $email;
	    $this->password = $password;
	    $this->createdAt = $createdAt;
	    $this->updatedAt = $updatedAt;
	    
    }
}
