<?php

/**
 * This file was automatically generated by the Awesome Conflex API Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Controller;

use MMWS\Model\Meal;
use MMWS\Entity\MealEntity;
use MMWS\Interfaces\AbstractController;
use MMWS\Model\Food;
use MMWS\Model\MealWithStats;
use MMWS\Model\Stats;

class MealController extends AbstractController
{
    public $entity;
    public $model;

    public function __construct(array $data = [])
    {
        $model = new Meal();
        foreach ($data as $key => $prop) {
            if (property_exists($model, $key)) {
                $model->{$key} = $prop;
            }
        }
        $this->entity = new MealEntity($model);
        $this->model = &$this->entity->model;
    }

    public function withFoodStats($meals)
    {

        if (!is_array($meals))
            $meals = [$meals];

        /**
         * @param Meal $meal
         */
        return array_map(function ($meal) {
            $ctl = new FoodController(['id' => $meal->id]);
            $food = $ctl->get([], true);
            if ($food instanceof Food) {
                $stats = new Stats($food, $meal->qtd);

                $withStats = new MealWithStats();
                $withStats->id = $meal->id;
                $withStats->stats = $stats;
                $withStats->food = $food;

                return $withStats;
            }
            return $meal;
        }, $meals);
    }
}
