<?php

/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Model;

use MMWS\Interfaces\AbstractModel;

class Diet extends AbstractModel
{
    /**
     * @var String $table the table name for this model;
     */
    public $table = 'diet';


    protected $id;
    protected $userId;
    protected $weight;
    protected $createdAt;
    protected $carb = 0;
    protected $prot = 0;
    protected $tfat = 0;
    protected $calories = 0;
    protected $act = 1;


    public function __construct($id = null, $userId = null, $weight = null, $createdAt = null, $carb = null, $prot = null, $tfat = null, $cal = null, $act = 1)
    {
        $this->id = $id;
        $this->userId = $userId;
        $this->weight = $weight;
        $this->createdAt = $createdAt;
        $this->carb = $carb;
        $this->prot = $prot;
        $this->tfat = $tfat;
        $this->calories = $cal ?? $this->prot * 4 + $this->carb * 4 + $this->tfat * 9;
        $this->act = $act;
    }

    public function calcCalories()
    {
        $this->calories = $this->prot * 4 + $this->carb * 4 + $this->tfat * 9;
    }
}
