<?php

/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Model;

use MMWS\Interfaces\AbstractModel;

class Food extends AbstractModel
{
    protected ?int $id;
    protected ?string $name;
    protected ?float $weight;
    protected ?int $userId;
    protected ?string $createdAt;
    protected ?float $carb;
    protected ?float $prot;
    protected ?float $tfat;
    protected ?float $fiber;
    protected ?float $sodium;
    protected ?float $cal;
    protected ?string $unit;
    protected ?int $act;

    public function __construct($id = null, $name = null, $weight = null, $userId = null, $createdAt = null, $carb = null, $prot = null, $tfat = null, $fiber = null, $sodium = null, $cal = null, $unit = null, $act = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->weight = $weight;
        $this->userId = $userId;
        $this->createdAt = $createdAt;
        $this->carb = $carb;
        $this->prot = $prot;
        $this->tfat = $tfat;
        $this->fiber = $fiber;
        $this->sodium = $sodium;
        $this->cal = $cal;
        $this->unit = $unit;
        $this->act = $act;
    }
}
