<?php

/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Model;

use MMWS\Interfaces\AbstractModel;

class Meal extends AbstractModel
{
    /**
     * @var String $table the table name for this model;
     */
    public $table = 'meal';


    protected $id;
    protected $dietId;
    protected $foodId;
    protected $qtd;
    protected $createdAt;
    protected $act;


    public function __construct($id = null, $dietId = null, $foodId = null, $qtd = null, $createdAt = null, $act = null)
    {
        $this->id = $id;
        $this->dietId = $dietId;
        $this->foodId = $foodId;
        $this->qtd = $qtd;
        $this->createdAt = $createdAt;
        $this->act = $act;
    }
}
