<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\OrderDetailEntity;
use MMWS\Interfaces\AbstractModel;

class OrderDetail extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'order_detail';


    public $detailId;
    public $token;
    public $key;
    public $password;
    public $orderId;
    public $accountFreed;
    

    public function __construct($detailId = null, $token = null, $key = null, $password = null, $orderId = null, $accountFreed = null)
    {
        $this->detailId = $detailId;
	    $this->token = $token;
	    $this->key = $key;
	    $this->password = $password;
	    $this->orderId = $orderId;
	    $this->accountFreed = $accountFreed;
	    
        $this->entity = new OrderDetailEntity($this);
    }
}