<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\PlatformsEntity;
use MMWS\Interfaces\AbstractModel;

class Platforms extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'platforms';


    public $platformId;
    public $platformName;
    public $platformCode;
    

    public function __construct($platformId = null, $platformName = null, $platformCode = null)
    {
        $this->platformId = $platformId;
	    $this->platformName = $platformName;
	    $this->platformCode = $platformCode;
	    
        $this->entity = new PlatformsEntity($this);
    }
}