<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\RobotOwnersEntity;
use MMWS\Interfaces\AbstractModel;

class RobotOwners extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'robot_owners';


    public $ownerId;
    public $ownerName;
    public $ownerToken;
    public $ownerKey;
    public $ownerEmail;
    

    public function __construct($ownerId = null, $ownerName = null, $ownerToken = null, $ownerKey = null, $ownerEmail = null)
    {
        $this->ownerId = $ownerId;
	    $this->ownerName = $ownerName;
	    $this->ownerToken = $ownerToken;
	    $this->ownerKey = $ownerKey;
	    $this->ownerEmail = $ownerEmail;
	    
        $this->entity = new RobotOwnersEntity($this);
    }
}