<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\RobotOrdersEntity;
use MMWS\Interfaces\AbstractModel;

class RobotOrders extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'robot_orders';


    public $orderId;
    public $ownerId;
    public $robotNumber;
    public $robotPlatform;
    public $orderExpiresAt;
    public $orderRenewExpiresAt;
    public $orderComment;
    public $status;
    

    public function __construct($orderId = null, $ownerId = null, $robotNumber = null, $robotPlatform = null, $orderExpiresAt = null, $orderRenewExpiresAt = null, $orderComment = null, $status = null)
    {
        $this->orderId = $orderId;
	    $this->ownerId = $ownerId;
	    $this->robotNumber = $robotNumber;
	    $this->robotPlatform = $robotPlatform;
	    $this->orderExpiresAt = $orderExpiresAt;
	    $this->orderRenewExpiresAt = $orderRenewExpiresAt;
	    $this->orderComment = $orderComment;
	    $this->status = $status;
	    
        $this->entity = new RobotOrdersEntity($this);
    }
}