<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\RobotAuthEntity;
use MMWS\Interfaces\AbstractModel;

class RobotAuth extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'robot_auth';


    public $authId;
    public $robotOrderId;
    public $authToken;
    public $authKey;
    public $fromIp;
    public $time;
    public $expired;
    

    public function __construct($authId = null, $robotOrderId = null, $authToken = null, $authKey = null, $fromIp = null, $time = null, $expired = null)
    {
        $this->authId = $authId;
	    $this->robotOrderId = $robotOrderId;
	    $this->authToken = $authToken;
	    $this->authKey = $authKey;
	    $this->fromIp = $fromIp;
	    $this->time = $time;
	    $this->expired = $expired;
	    
        $this->entity = new RobotAuthEntity($this);
    }
}