<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\ShowOrdersListEntity;
use MMWS\Interfaces\AbstractModel;

class ShowOrdersList extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'show_orders_list';


    public $orderId;
    public $robotNumber;
    public $expiresAt;
    public $renewExpiresAt;
    public $comment;
    public $token;
    public $key;
    public $password;
    public $accountFreed;
    public $robotPrice;
    public $robotDescription;
    public $ownerName;
    public $ownerId;
    public $platformName;
    public $platformCode;
    

    public function __construct($orderId = null, $robotNumber = null, $expiresAt = null, $renewExpiresAt = null, $comment = null, $token = null, $key = null, $password = null, $accountFreed = null, $robotPrice = null, $robotDescription = null, $ownerName = null, $ownerId = null, $platformName = null, $platformCode = null)
    {
        $this->orderId = $orderId;
	    $this->robotNumber = $robotNumber;
	    $this->expiresAt = $expiresAt;
	    $this->renewExpiresAt = $renewExpiresAt;
	    $this->comment = $comment;
	    $this->token = $token;
	    $this->key = $key;
	    $this->password = $password;
	    $this->accountFreed = $accountFreed;
	    $this->robotPrice = $robotPrice;
	    $this->robotDescription = $robotDescription;
	    $this->ownerName = $ownerName;
	    $this->ownerId = $ownerId;
	    $this->platformName = $platformName;
	    $this->platformCode = $platformCode;
	    
        $this->entity = new ShowOrdersListEntity($this);
    }
}