<?php

/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */

namespace MMWS\Model;

use MMWS\Interfaces\AbstractModel;

class User extends AbstractModel
{
    /**
     * @var String $table the table name for this model;
     */
    public $table = 'user';


    protected ?int $id;
    protected ?string $name;
    protected ?string $email;
    protected ?string $password;
    protected ?\DateTime $createdAt;
    protected ?\DateTime $updatedAt;


    public function __construct(?int $id = null, ?string $name = null, ?string $email = null, ?string $password = null, ?\DateTime $createdAt = null, ?\DateTime $updatedAt = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->email = $email;
        $this->password = $password;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }

    public function encryptPassword()
    {
        return password_hash($this->password, PASSWORD_BCRYPT);
    }

    public function matchPassword(string $raw)
    {
        return password_verify($raw, $this->password);
    }
}
