<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\UsersEntity;
use MMWS\Interfaces\AbstractModel;

class Users extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'users';


    public $id;
    public $name;
    public $email;
    public $password;
    public $createdAt;
    public $updatedAt;
    

    public function __construct($id = null, $name = null, $email = null, $password = null, $createdAt = null, $updatedAt = null)
    {
        $this->id = $id;
	    $this->name = $name;
	    $this->email = $email;
	    $this->password = $password;
	    $this->createdAt = $createdAt;
	    $this->updatedAt = $updatedAt;
	    
        $this->entity = new UsersEntity($this);
    }
}