<?php
/**
 * This file was automatically generated by the Awesome Conflex Webservice Model Generator Module
 * based in MYSQL/Mariadb database tables. After the generation you can modify
 * this model to fill with the best methods you think it should have.
 * 
 * 
 * Take care of this template and abuse of this.
 * 
 * Thank you for using it. github.com/mury12
 * 
 */
 
namespace MMWS\Model;
use MMWS\Entity\UsersEntity;
use MMWS\Interfaces\AbstractModel;

class Users extends AbstractModel
{

    /**
     * @var String $table the table name for this model;
     */   
    public $table = 'users';


    public $userId;
    public $userName;
    public $userPass;
    public $registeredAt;
    public $lastLogin;
    public $userEmail;
    

    public function __construct($userId = null, $userName = null, $userPass = null, $registeredAt = null, $lastLogin = null, $userEmail = null)
    {
        $this->userId = $userId;
	    $this->userName = $userName;
	    $this->userPass = $userPass;
	    $this->registeredAt = $registeredAt;
	    $this->lastLogin = $lastLogin;
	    $this->userEmail = $userEmail;
	    
        $this->entity = new UsersEntity($this);
    }
}